//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

package v1alpha1

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in CVSS) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.CVSS"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerRef) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.ContainerRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerResult) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.ContainerResult"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ContainerStatus) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.ContainerStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Image) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.Image"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ImageLayer) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.ImageLayer"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ImageList) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.ImageList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ImageMetadata) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.ImageMetadata"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ImageRef) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.ImageRef"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ImageStatus) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.ImageStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in ImageWorkloadScanReports) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.ImageWorkloadScanReports"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Report) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.Report"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Result) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.Result"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SBOM) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.SBOM"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in SBOMList) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.SBOMList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Summary) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.Summary"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VEXStatus) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.VEXStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in Vulnerability) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.Vulnerability"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VulnerabilityReport) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.VulnerabilityReport"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in VulnerabilityReportList) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.VulnerabilityReportList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadScanReport) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.WorkloadScanReport"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadScanReportList) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.WorkloadScanReportList"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadScanReportSpec) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.WorkloadScanReportSpec"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadScanReportStatus) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.WorkloadScanReportStatus"
}

// OpenAPIModelName returns the OpenAPI model name for this type.
func (in WorkloadScanVulnerabilityReport) OpenAPIModelName() string {
	return "storage.sbomscanner.kubewarden.io.v1alpha1.WorkloadScanVulnerabilityReport"
}
